# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    marketplace.http_client:
        class: Symfony\Contracts\HttpClient\HttpClientInterface
        factory: ['Symfony\Component\HttpClient\HttpClient', 'create']
        arguments:
            - base_uri: '%env(SUPABASE_API_BASE)%'

when@test:
    services:
        App\Tests\Mock\Auth0MockHttpClient:
            class: App\Tests\Mock\Auth0MockHttpClient

        App\Tests\Mock\SupabaseMockHttpClient:
            class: App\Tests\Mock\SupabaseMockHttpClient

        App\Auth0\Auth0Client:
            autowire: true
            arguments:
                $httpClient: '@App\Tests\Mock\Auth0MockHttpClient'

        App\Supabase\SupabaseClient:
            autowire: true
            arguments:
                $httpClient: '@App\Tests\Mock\SupabaseMockHttpClient'
